version: '3'

services:
  db:
    image: postgres:15-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: psw
      POSTGRES_DB: bank
